markdown: kramdown
name: Justice Divided
url: https://justice-divided.datamade.us
encoding: utf-8
timezone: America/Chicago
description: "tk"
baseurl: /justice-divided
google_api_key: AIzaSyCgGoW9eDO-q9QLJMazPEAkndffEpJr-hw