GENERATED_FILES=output/arrests-14.csv output/disp-by-dist-14.csv output/djj_exits.csv

include arrests.mk djj_exits.mk dispositions.mk

.PHONY : all
all : $(GENERATED_FILES)

.PHONY : clean
clean :
	rm output/*